### ISSUE TITLE
[앱 심사] 1.0.0.3 심사 리젝 대응

### ISSUE THREAD

**Issue by choiapril6** [bside-tinkerbell/Waving-iOS#85]
## To-Do
- [x] 계정 탈퇴 기능 추가
- [x] 계정 탈퇴 시 confirmation step 있어야 함
- [x] 인사말 리스트 > 인사말 복사 버튼 동작 안 하는 버그
- [x] 가입 완료 화면에서 'next' 버튼 동작 안 하는 버그
- [x] 나의 지인 화면에서 이름 탭했을 때 동작 안 하는 버그

## 1.0.0.3 리뷰 결과 원문
> Hello,
> 
> Thank you for your resubmission. Upon further review, we identified an additional issue that needs your attention. See below for more information.
> 
> If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know. 
> 
> 
> Guideline 5.1.1(v) - Data Collection and Storage
> 
> We noticed that your app supports account creation but does not appear to include an option to initiate account deletion. 
> 
> Apps that support account creation must also offer account deletion to give App Store users more control of the data they've shared while using your app.
> 
> Next Steps
> 
> If your app already supports account deletion, reply to this message and let us know how to locate this feature. If your app does not support account deletion, revise your app to include an option to initiate account deletion and delete all user data you are not legally required to retain. 
> 
> If you are unable to offer account deletion or need to provide additional customer service flows to facilitate and confirm account deletion, either because your app operates in a highly-regulated industry or for some other reason, reply to this message in App Store Connect and provide additional information or documentation. If you have questions regarding your legal obligations, check with your legal counsel.
> 
> Keep these requirements in mind when updating your app to support account deletion: 
> 
> - Only offering to temporarily deactivate or disable an account is insufficient.
> - If users need to visit a website to finish deleting their account, include a link directly to the page on your website where they can complete the process.
> - You may include confirmation steps to prevent users from accidentally deleting their account. However, only apps in highly-regulated industries may require users to use customer service resources, such as making a phone call or sending an email, to complete account deletion.
> 
> Resources 
> 
> - Review frequently asked questions and learn more about the [account deletion requirements](https://developer.apple.com/support/offering-account-deletion-in-your-app). 
> 
> Guideline 2.1 - Performance - App Completeness
> 
> We discovered one or more bugs in your app. Specifically, when we tapped a 인사말, it did not copy the text. And also when we tapped the next button on registration page or name on 나의 지인 page, your app produced no further action. Please review the details below and complete the next steps. 
> 
> Review device details:
> 
> - Device type: iPad 
> - OS version: iOS 17.0.3
> 
> Next Steps
> 
> Please run your app on a device to reproduce the issues, then revise and submit your app for review. If at first you're unable to reproduce the issue, try the following: 
> 
> - For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce. 
> - For app updates, install the new version as an update to the previous version, then follow the steps to reproduce.
> 
> If we misunderstood the intended behavior of your app, please reply to this message in App Store Connect to provide information on how these features were intended to work.
> 
> Please see attached screenshots for details.

**Comment by choiapril6** [comment]
# 나의 지인 화면에서 이름 탭했을 때 동작 안 하는 버그
## 원인
- 나의 지인 저장할 때 아래 요청 시 에러 발생함
- 폰 번호의 포맷을 서버와 맞춰야 함
- 원우님에게 확인 받은 서버 폰 넘버 형식: 010-1234-5678
<img width="500" alt="스크린샷 2023-12-09 오후 8 18 29" src="https://github.com/bside-tinkerbell/Waving-iOS/assets/3433224/9bdeb9c4-5cf6-4273-833b-de5c395da76d">
## 해결방안
- PhoneNumberKit (spm) 을 이용해 폰 번호 포매팅 시도
- 문제: 포맷 결과가 이런 형식임 (Formatted Number: +821012345678, expected: 010-1234-5678)
